2025-06-10 12:27:23,477 - . - INFO - run run-segmentation with args:Namespace(segmentation_algorithm='p30-E165_R2_default_1_ZLevel_cpsam.json', input_images='/beegfs/scratch/ric.broccoli/kubacki.michal/SPATIAL_data/data_p30-E165/R2/images/mosaic_(?P<stain>[\\w|-]+)_z(?P<z>[0-9]+).tif', input_micron_to_mosaic='/beegfs/scratch/ric.broccoli/kubacki.michal/SPATIAL_data/data_p30-E165/R2/images/micron_to_mosaic_pixel_transform.csv', output_path='p30-E165_R2_default_1_ZLevel_cpsam', tile_size=2400, tile_overlap=200, max_row_group_size=17500, overwrite=True)
2025-06-10 12:27:23,810 - . - INFO - installed versions:
python 3.9.23 | packaged by conda-forge | (main, Jun  4 2025, 17:57:12) 
[GCC 13.3.0]
vpt 1.3.0
vpt_core 1.2.0
vpt_plugin_cellpose 1.0.2
vpt_plugin_watershed 1.0.2
geopandas 0.14.4
shapely 2.0.7
s3fs 2024.2.0
gcsfs 2024.2.0
rasterio 1.3.5.post1
cellpose 1.0.2
stardist 0.8.3
2025-06-10 12:27:23,814 - . - INFO - run_segmentation started
2025-06-10 12:27:23,945 - . - INFO - prepare segmentation started
2025-06-10 12:27:45,492 - . - INFO - prepare segmentation finished
[########################################] | 100% Completed |  0.0s[2K2025-06-10 12:27:51,738 - ./task-194 - INFO - Run segmentation on tile 194 started
2025-06-10 12:27:51,744 - ./task-194 - INFO - Tile 194 [36400, 26000, 2800, 2800]
2025-06-10 12:27:51,794 - ./task-198 - INFO - Run segmentation on tile 198 started
2025-06-10 12:27:51,798 - ./task-196 - INFO - Run segmentation on tile 196 started
2025-06-10 12:27:51,849 - ./task-198 - INFO - Tile 198 [0, 28600, 2800, 2800]
2025-06-10 12:27:51,849 - ./task-196 - INFO - Tile 196 [41600, 26000, 2800, 2800]
2025-06-10 12:28:17,759 - ./task-198 - ERROR - exception of type <class 'TypeError'> thrown: __init__() got an unexpected keyword argument 'min_size'
2025-06-10 12:28:17,778 - ./task-192 - INFO - Run segmentation on tile 192 started
2025-06-10 12:28:17,786 - ./task-192 - INFO - Tile 192 [31200, 26000, 2800, 2800]
2025-06-10 12:28:17,874 - ./task-196 - ERROR - exception of type <class 'TypeError'> thrown: __init__() got an unexpected keyword argument 'min_size'
2025-06-10 12:28:19,249 - ./task-194 - ERROR - exception of type <class 'TypeError'> thrown: __init__() got an unexpected keyword argument 'min_size'
2025-06-10 12:28:20,207 - ./task-192 - ERROR - exception of type <class 'TypeError'> thrown: __init__() got an unexpected keyword argument 'min_size'
2025-06-10 12:28:21,269 - . - ERROR - exception of type <class 'TypeError'> thrown: __init__() got an unexpected keyword argument 'min_size'
2025-06-10 12:28:21,270 - . - ERROR - vpt has encountered a runtime error (__init__() got an unexpected keyword argument 'min_size') and will now exit
